(function(){'use strict';
const $=id=>document.getElementById(id),KEY='pnr-lab-v3',LEGACY_KEY='pnr-lab-v2',ids=['symbol','spot','nlv','asOf','epr','rate','yield','evaluateOn','evaluateSpot','ivScale','deposit','cost','brokerPNR','brokerMargin','brokerExtrinsic'];
let state={original:[],proposed:[]},last=null,chartData=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>Number.isFinite(x)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x):'—';
const pct=x=>Number.isFinite(x)?x.toFixed(2)+'%':'—';
const sign=x=>x>0?'+':'';
function defaults(){const today=new Date().toLocaleDateString('en-CA');const date=/^\d{4}-\d{2}-\d{2}$/.test(today)?today:new Date().toISOString().slice(0,10);return{symbol:'',spot:100,nlv:100000,asOf:date,epr:25,rate:0,yield:0,evaluateOn:date,evaluateSpot:100,ivScale:1,deposit:0,cost:0,brokerPNR:'',brokerMargin:'',brokerExtrinsic:'',original:[],proposed:[]};}
function example(){const data=defaults(),base=Date.parse(data.asOf+'T00:00:00Z'),date=n=>new Date(base+n*86400000).toISOString().slice(0,10),r=(kind,qty,expiry,strike,mark)=>({kind,qty,expiry,strike,mark,iv:'',entry:'',priceSource:'Synthetic sample midpoint'});const original=[r('put',-2,date(45),75,.80),r('call',-2,date(45),125,.90),r('put',-1,date(90),65,.60),r('call',-1,date(90),140,.50)];return{...data,symbol:'XYZ',spot:100,nlv:100000,evaluateSpot:100,original,proposed:JSON.parse(JSON.stringify(original))};}
function allInputs(){const data={...state};for(const id of ids)data[id]=$(id).value;return data;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(allInputs()));$('save-status').textContent='Saved on this browser · Export a JSON backup to move between devices.';}catch(e){$('save-status').textContent='Browser storage unavailable. Use Export inputs to keep a backup.';}}
function dirty(){last=null;$('results').hidden=true;$('errors').textContent='';save();}
function load(data){if(!data||!Array.isArray(data.original)||!Array.isArray(data.proposed))throw Error('Invalid project: expected original and proposed position arrays.');if(data.original.length>200||data.proposed.length>200)throw Error('Maximum 200 legs per table.');const def=defaults();state={original:data.original.map(cleanRow),proposed:data.proposed.map(cleanRow)};for(const id of ids)$(id).value=data[id]??def[id];renderTables();dirty();}
function cleanRow(x){if(!x||typeof x!=='object')throw Error('Invalid position row.');return{kind:x.kind??'call',qty:x.qty??-1,expiry:x.expiry??'',strike:x.strike??'',mark:x.mark??'',iv:x.iv??'',entry:x.entry??'',priceSource:x.priceSource??'Manual mark'};}
function renderTables(){for(const side of ['original','proposed'])$(side).innerHTML=state[side].map((r,i)=>`<tr data-row="${i}" data-side="${side}"><td><select data-field="kind" aria-label="${side} row ${i+1} type">${['call','put','stock'].map(k=>`<option value="${k}" ${r.kind===k?'selected':''}>${k==='stock'?'Shares':k[0].toUpperCase()+k.slice(1)}</option>`).join('')}</select></td>${['qty','expiry','strike','mark','iv','entry'].map(k=>`<td><input data-field="${k}" aria-label="${side} row ${i+1} ${k}" type="${k==='expiry'?'date':'number'}" ${k==='expiry'?'':`step="${k==='qty'?'1':'any'}"`} value="${esc(r[k])}" ${(r.kind==='stock'&&['expiry','strike','mark','iv'].includes(k))?'disabled':''} ${k==='iv'?'placeholder="Auto"':''}>${k==='mark'&&r.kind!=='stock'?'<small class="hint">'+esc(r.priceSource||'Manual mark')+'</small>':''}</td>`).join('')}<td><button class="remove" data-remove="${i}" data-side="${side}" aria-label="Remove ${side} row ${i+1}">×</button></td></tr>`).join('');}
for(const side of ['original','proposed']){
 $(side).addEventListener('input',e=>{const field=e.target.dataset.field;if(!field)return;const row=e.target.closest('tr'),raw=e.target.value;state[side][+row.dataset.row][field]=['kind','expiry'].includes(field)?raw:(raw===''?'':Number(raw));if(field==='mark'){state[side][+row.dataset.row].priceSource='Manual mark';const note=e.target.parentElement?.querySelector('small');if(note)note.textContent='Manual mark';}dirty();});
 $(side).addEventListener('change',e=>{if(e.target.dataset.field==='kind'){renderTables();dirty();}});
 $(side).addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){state[side].splice(+b.dataset.remove,1);renderTables();dirty();}});
}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const snapshot=Date.parse($('asOf').value+'T00:00:00Z');if(!Number.isFinite(snapshot)){$('errors').textContent='Enter a valid snapshot date before adding a leg.';return;}const expiry=new Date(snapshot+45*86400000).toISOString().slice(0,10);state[b.dataset.add].push({kind:'call',qty:-1,expiry,strike:+$('spot').value*1.2,mark:'',iv:'',entry:''});renderTables();dirty();});
for(const id of ids)$(id).addEventListener('input',dirty);
$('copy').onclick=()=>{state.proposed=JSON.parse(JSON.stringify(state.original));renderTables();dirty();};
$('empty').onclick=()=>{if(confirm('Clear both position tables and reset account inputs?'))load(defaults());};
$('demo').onclick=()=>{if(state.original.length&&!confirm('Replace current inputs with synthetic sample data? Export your inputs first to keep them.'))return;load(example());calculate();};
$('today').onclick=()=>{$('evaluateOn').value=$('asOf').value;$('evaluateSpot').value=$('spot').value;dirty();calculate();};
$('week').onclick=()=>{const d=Date.parse($('asOf').value+'T00:00:00Z');if(!Number.isFinite(d))return;$('evaluateOn').value=new Date(d+7*86400000).toISOString().slice(0,10);$('evaluateSpot').value=$('spot').value;dirty();calculate();};
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('export').onclick=()=>download('pnr-lab-inputs.json',JSON.stringify({version:1,...allInputs()},null,2),'application/json');
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Project file is too large.');load(JSON.parse(await f.text()));calculate();}catch(err){$('errors').textContent=err.message;}e.target.value='';};
for(const id of ['bid','ask'])$(id).oninput=()=>{const b=$('bid').value,a=$('ask').value;$('mid-output').textContent=b!==''&&a!==''&&+a>=+b?'Midpoint: $'+((+b + +a)/2).toFixed(4):'Midpoint: — (ask must be ≥ bid)';};
function config(){const c={};for(const id of ids)c[id]=['symbol','asOf','evaluateOn'].includes(id)?$(id).value:Number($(id).value);for(const k of ['spot','nlv','epr','rate','yield','evaluateSpot','ivScale','deposit','cost'])if($(k).value===''||!Number.isFinite(c[k]))throw Error('Enter a valid value for '+k+'.');if(c.cost<0)throw Error('Fees and adverse slippage must be nonnegative.');if(Math.abs(c.rate)>100||Math.abs(c.yield)>100)throw Error('Rate and yield must be between −100% and 100%.');return c;}
function metricRoot(root,up){return root?(up?'+':'−')+pct(root.move):'No crossing found';}
function eprBoundary(result,cfg){if(!result.up)return{price:null,move:null};const price=result.up.price/(1+cfg.epr/100);return{price,move:(price/cfg.evaluateSpot-1)*100};}
function card(name,result,cls){const u=result.up,inside=(u&&u.move<last.cfg.epr)||(result.down&&result.down.move<last.cfg.epr),boundary=eprBoundary(result,last.cfg);return`<div class="result-card ${cls}"><div class="card-label">${name} · estimated upside PNR</div><div class="pnr-number">${u?'+'+pct(u.move):'<small>No crossing found</small>'}</div><div class="card-stats"><span>Zero-equity price<strong>${u?money(u.price):'Beyond search range'}</strong></span><span>PNR = EPR price<strong>${boundary.price!=null?money(boundary.price):'—'}</strong></span><span>Rally until PNR = EPR<strong>${boundary.move!=null?(boundary.move>0?'+'+pct(boundary.move):'Already inside EPR'):'—'}</strong></span><span>Projected NLV<strong>${money(result.equity)}</strong></span><span>Downside PNR<strong>${metricRoot(result.down,false)}</strong></span></div><span class="badge ${inside||result.equity<=0?'warn':''}">${result.equity<=0?'Projected NLV ≤ 0':u?(inside?'Inside EPR boundary':'Outside EPR boundary'):(inside?'Downside inside EPR boundary':'No upside crossing in search range')}</span>${boundary.move!=null?`<p class="hint">Conditional estimate: zero-equity price ÷ (1 + EPR). Time, IV and NLV changes can move this boundary.</p>`:''}</div>`;}
function calculate(){try{
 const cfg=config();let a,b;try{a=PNR.compile(state.original,cfg);}catch(e){throw Error('Original — '+e.message);}try{b=PNR.compile(state.proposed,cfg);}catch(e){throw Error('Proposed — '+e.message);}
 const original=PNR.evaluate(a,cfg),proposed=PNR.evaluate(b,cfg,cfg.deposit,cfg.cost);last={cfg,original,proposed};$('errors').textContent='';$('results').hidden=false;
 $('result-heading').textContent=(cfg.symbol||'Underlying')+' · '+cfg.evaluateOn+' at '+money(cfg.evaluateSpot);
 $('cards').innerHTML=card('Original',original,'')+card('Proposed',proposed,'proposed-card');
 const originalBoundary=eprBoundary(original,cfg),proposedBoundary=eprBoundary(proposed,cfg),rows=[['Upside PNR',original.up?.move,proposed.up?.move,'pp'],['Rally until upside PNR equals EPR',originalBoundary.move,proposedBoundary.move,'pp'],['Price where upside PNR equals EPR',originalBoundary.price,proposedBoundary.price,'$'],['Downside PNR magnitude',original.down?.move,proposed.down?.move,'pp'],['Projected account NLV',original.equity,proposed.equity,'$'],['Additional loss at +'+cfg.epr+'% EPR',original.upLoss,proposed.upLoss,'$'],['Additional loss at −'+cfg.epr+'% EPR',original.downLoss,proposed.downLoss,'$'],['Equity left at up EPR',original.equity-original.upLoss,proposed.equity-proposed.upLoss,'$'],['Equity left at down EPR',original.equity-original.downLoss,proposed.equity-proposed.downLoss,'$']];
 $('comparison').innerHTML=rows.map(([name,a,b,type])=>{const d=b-a,fmt=x=>type==='pp'?pct(x):money(x);return`<tr><td>${esc(name)}</td><td>${fmt(a)}</td><td>${fmt(b)}</td><td>${Number.isFinite(a)&&Number.isFinite(b)?(type==='pp'?sign(d)+d.toFixed(2)+' pp':sign(d)+money(d)):'—'}</td></tr>`;}).join('');
 const notes=['EPR stress prices: '+money(original.stressDown)+' / '+money(original.stressUp)+'.'];if(original.expired||proposed.expired)notes.push('Some options expire on or before this date: intrinsic settlement is used. Enter resulting shares manually after exercise/assignment.');if(original.fitMismatch||proposed.fitMismatch)notes.push('An IV override differs from its quoted midpoint by over $0.02. P/L is anchored to the modeled current price.');if(!state.original.length)notes.push('Original table is empty; only cash equity is modeled.');$('result-note').textContent=notes.join(' ');
 renderBenchmark(a,cfg);renderLegs();drawChart();save();
 }catch(e){last=null;$('results').hidden=true;$('errors').textContent=e.message;}}
function renderBenchmark(legs,cfg){
 const b=PNR.evaluate(legs,{...cfg,evaluateOn:cfg.asOf,evaluateSpot:cfg.spot,ivScale:1});
 const nearest=b.up&&(!b.down||b.up.move<=b.down.move)?b.up.move:b.down?-b.down.move:null;
 const observed=$('brokerPNR').value===''?null:Number($('brokerPNR').value),observedMargin=$('brokerMargin').value===''?null:Number($('brokerMargin').value),observedExt=$('brokerExtrinsic').value===''?null:Number($('brokerExtrinsic').value);
 const ext=legs.reduce((total,l)=>l.kind==='stock'?total:total-l.qty*100*(l.base-Math.max(l.kind==='call'?cfg.spot-l.strike:l.strike-cfg.spot,0)),0);
 const fmtMoney=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):'—';
 const gap=observed!=null&&Math.abs(observed)<100&&nearest!=null?nearest-observed:null;
 $('broker-comparison').innerHTML=[['Nearest signed PNR',observed==null?'Not supplied':pct(observed),nearest==null?'No crossing found':pct(nearest),gap==null?'—':sign(gap)+gap.toFixed(2)+' pp'],['Underlying margin requirement',fmtMoney(observedMargin),'Not modeled','—'],['Net short option extrinsic value',fmtMoney(observedExt),fmtMoney(ext),observedExt==null?'—':fmtMoney(ext-observedExt)]].map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('');
 $('broker-note').textContent='Original positions at the snapshot date and price; no proposed cash or future IV shock. Broker inputs are references, never fitted targets. A whole-percent PNR does not establish the broker’s rounding rule. 101% readings are not treated as exact zero-equity thresholds. Margin uses separate broker price/IV stress arrays and house rules. EPR loss is not margin.';
}
$('calculate').onclick=calculate;$('leg-side').onchange=renderLegs;
function legName(l){return (l.qty<0?'Short ':'Long ')+Math.abs(l.qty)+' '+(l.kind==='stock'?'shares':l.expiry+' $'+l.strike+' '+l.kind);}
function renderLegs(){if(!last)return;const data=last[$('leg-side').value].legResults;$('leg-results').innerHTML=data.map(l=>`<tr><td>${esc(legName(l))}</td><td>${l.kind==='stock'?'—':pct(l.iv*100)}</td><td class="${l.dayPL>=0?'positive':'negative'}">${money(l.dayPL)}</td><td>${money(l.upLoss)}</td><td>${money(l.perContractUp)}</td><td>${money(l.downLoss)}</td></tr>`).join('')||'<tr><td colspan="6">No active positions.</td></tr>';}
function drawChart(){if(!last)return;const canvas=$('chart'),rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,w=Math.max(300,rect.width),h=300;canvas.width=w*ratio;canvas.height=h*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const pad={l:72,r:22,t:18,b:36},cfg=last.cfg;const roots=[last.original.up?.move,last.proposed.up?.move].filter(Number.isFinite);const xmin=-Math.min(90,Math.max(40,cfg.epr*1.4)),xmax=Math.min(150,Math.max(45,...roots.map(x=>x+8),cfg.epr*1.4));
 const data=[];for(let i=0;i<=180;i++){const move=xmin+(xmax-xmin)*i/180,s=cfg.evaluateSpot*(1+move/100);data.push({move,a:last.original.equityAt(s),b:last.proposed.equityAt(s)});}const values=data.flatMap(d=>[d.a,d.b]);const ymin=Math.min(0,...values),ymax=Math.max(1,...values),span=ymax-ymin,low=ymin-span*.05,high=ymax+span*.08;const x=m=>pad.l+(m-xmin)/(xmax-xmin)*(w-pad.l-pad.r),y=v=>h-pad.b-(v-low)/(high-low)*(h-pad.t-pad.b);ctx.font='11px system-ui';ctx.lineWidth=1;
 for(let i=0;i<=4;i++){const v=low+(high-low)*i/4;ctx.strokeStyle='#26374b';ctx.beginPath();ctx.moveTo(pad.l,y(v));ctx.lineTo(w-pad.r,y(v));ctx.stroke();ctx.fillStyle='#9aadc0';ctx.textAlign='right';ctx.fillText(money(v),pad.l-8,y(v)+4);}for(let i=0;i<=5;i++){const m=xmin+(xmax-xmin)*i/5;ctx.textAlign='center';ctx.fillStyle='#9aadc0';ctx.fillText(m.toFixed(0)+'%',x(m),h-12);}ctx.strokeStyle='#ffd39b';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(pad.l,y(0));ctx.lineTo(w-pad.r,y(0));ctx.stroke();ctx.setLineDash([]);
 for(const [key,color] of [['a','#91b5ff'],['b','#8eedb4']]){ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();data.forEach((d,i)=>i?ctx.lineTo(x(d.move),y(d[key])):ctx.moveTo(x(d.move),y(d[key])));ctx.stroke();}
 chartData={data,xmin,xmax,w,pad,cfg};}
window.addEventListener('resize',()=>{if(last)drawChart();});
$('chart').addEventListener('pointermove',e=>{if(!chartData)return;const d=chartData,px=e.clientX-$('chart').getBoundingClientRect().left,m=d.xmin+(px-d.pad.l)/(d.w-d.pad.l-d.pad.r)*(d.xmax-d.xmin),i=Math.max(0,Math.min(d.data.length-1,Math.round((m-d.xmin)/(d.xmax-d.xmin)*(d.data.length-1)))),p=d.data[i];$('chart-hover').textContent='Move '+sign(p.move)+p.move.toFixed(1)+'% · Price '+money(d.cfg.evaluateSpot*(1+p.move/100))+' · Original NLV '+money(p.a)+' · Proposed NLV '+money(p.b);});
$('csv').onclick=()=>{if(!last)return;const out=[['Portfolio','Position','Fitted IV percent','Projected P/L','Up EPR loss','Up loss per contract','Down EPR loss']];for(const side of ['original','proposed'])for(const l of last[side].legResults)out.push([side,legName(l),l.kind==='stock'?'':l.iv*100,l.dayPL,l.upLoss,l.perContractUp,l.downLoss]);const csv=out.map(row=>row.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n');download('pnr-lab-leg-results.csv',csv,'text/csv');};
try{const saved=localStorage.getItem(KEY),legacy=!saved&&localStorage.getItem(LEGACY_KEY);if(saved)load(JSON.parse(saved));else if(legacy){const migrated=JSON.parse(legacy);migrated.rate=0;migrated.yield=0;load(migrated);save();}else load(defaults());if(state.original.length)calculate();}catch(e){load(defaults());$('save-status').textContent='Could not restore saved inputs. Restore your JSON backup or start a new comparison.';}
window.PNRLab={snapshot:allInputs,importRows(rows,side,append,fields){if(!['original','proposed'].includes(side))throw Error('Choose an import target.');if(rows.length+(append?state[side].length:0)>200)throw Error('Maximum 200 legs per table.');state[side]=append?[...state[side],...rows.map(cleanRow)]:rows.map(cleanRow);if(fields)for(const id of ['symbol','spot','nlv'])if(fields[id]!==''&&fields[id]!=null)$(id).value=fields[id];if(fields?.spot){$('evaluateSpot').value=fields.spot;}renderTables();dirty();}};
})();
