(function(){'use strict';
const $=id=>document.getElementById(id);let rows=[],previewURLs=[],busy=false,enginePromise=null,selectedFiles=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function progress(text){$('ocr-progress').textContent=text;}
function updateApply(){const date=/^\d{4}-\d{2}-\d{2}$/;$('ocr-apply').disabled=busy||!rows.length||rows.some(r=>!r.confirmed||r.qty===''||!Number.isInteger(+r.qty)||+r.qty===0||!date.test(r.expiry)||!(+r.strike>0)||!(+r.mark>0));}
function render(){$('ocr-review').hidden=false;$('ocr-rows').innerHTML=rows.map((r,i)=>`<tr data-ocr-row="${i}"><td><input data-field="confirmed" type="checkbox" ${r.confirmed?'checked':''} aria-label="Confirm extracted row ${i+1}"></td><td><select data-field="kind" aria-label="Extracted row ${i+1} type"><option value="call" ${r.kind==='call'?'selected':''}>Call</option><option value="put" ${r.kind==='put'?'selected':''}>Put</option></select></td>${['qty','expiry','strike','bid','ask','last','entry','mark'].map(k=>`<td><input data-field="${k}" type="${k==='expiry'?'date':'number'}" ${k==='expiry'?'':`step="${k==='qty'?1:'any'}"`} value="${esc(r[k])}" aria-label="Extracted row ${i+1} ${k}"></td>`).join('')}<td class="ocr-warnings">${esc((r.warnings||[]).join(' · ')||'Verify all fields')}</td><td><button data-ocr-remove="${i}" class="remove" aria-label="Remove extracted row ${i+1}">×</button></td></tr>`).join('');updateApply();}
function show(parsed){rows=parsed.rows;$('ocr-symbol').value=parsed.symbol||'';$('ocr-spot').value=parsed.spot||'';$('ocr-nlv').value=parsed.nlv||'';$('ocr-text').value=parsed.text||'';$('ocr-fields').checked=false;render();progress(parsed.message|| (rows.length?'Found '+rows.length+' candidate legs. Check every row and confirm the quantity sign, year, strike and midpoint.':'No clear positions-list rows found. Use the text fallback, crop to the positions list, or add review rows manually.'));}
function loadEngine(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(enginePromise)return enginePromise;enginePromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';s.onload=()=>{if(window.Tesseract)resolve(window.Tesseract);else{enginePromise=null;reject(Error('OCR engine failed to initialize.'));}};s.onerror=()=>{enginePromise=null;s.remove();reject(Error('Cannot download OCR engine. Check internet access or use the text fallback.'));};document.head.appendChild(s);});return enginePromise;}
function selectImages(files){const candidates=[...(files||[])];if(candidates.length>2){selectedFiles=[];$('screenshot-file').value='';$('photo-count').textContent='No photos selected · maximum 2';progress('Choose no more than two photos.');return;}if(!candidates.length)return;if(candidates.some(file=>!(file.type||'').startsWith('image/'))){progress('Choose photos or screenshot images only.');return;}selectedFiles=candidates;for(const url of previewURLs)URL.revokeObjectURL(url);previewURLs=selectedFiles.map(file=>URL.createObjectURL(file));for(let i=0;i<2;i++){const img=$(i?'ocr-image-2':'ocr-image');if(previewURLs[i]){img.src=previewURLs[i];img.hidden=false;}else{img.removeAttribute?.('src');img.hidden=true;}}$('photo-count').textContent=selectedFiles.length+' photo'+(selectedFiles.length===1?'':'s')+' selected: '+selectedFiles.map(f=>f.name||'photo').join(' + ');progress('Ready to read '+selectedFiles.length+' photo'+(selectedFiles.length===1?'':'s')+'.');}
async function prepare(file){if(!(file.type||'').startsWith('image/'))throw Error('Choose a photo or screenshot image.');if(file.size>20000000)throw Error('Use images under 20 MB each.');const image=new Image(),url=URL.createObjectURL(file);try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('This browser could not decode an image. If it is HEIC, export it as JPEG or PNG and try again.'));image.src=url;});}finally{URL.revokeObjectURL(url);}if(image.width*image.height>30000000)throw Error('An image is too large. Crop it to the positions list.');const scale=Math.min(2,1800/image.width,4000/image.height),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);let sum=0,count=0;for(let i=0;i<pixels.data.length;i+=400){sum+=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];count++;}const invert=sum/count<128;for(let i=0;i<pixels.data.length;i+=4){let g=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];if(invert)g=255-g;g=Math.max(0,Math.min(255,(g-128)*1.7+128));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=g;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);return canvas;}
function wordsFrom(data){const words=[];for(const block of data.blocks||[])for(const paragraph of block.paragraphs||[])for(const line of paragraph.lines||[])for(const word of line.words||[])words.push(word);return words;}
$('screenshot-file').onchange=e=>selectImages(e.target.files);
$('ocr-read').onclick=async()=>{if(busy)return;if(!selectedFiles.length){progress('Upload one or two photos first.');return;}let worker=null,active=0;busy=true;$('ocr-read').disabled=true;updateApply();try{const T=await loadEngine();worker=await T.createWorker('eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@6.0.0',logger:m=>progress('Photo '+(active+1)+' of '+selectedFiles.length+' · '+m.status+(m.progress!=null?' · '+Math.round(m.progress*100)+'%':''))});await worker.setParameters({tessedit_pageseg_mode:T.PSM.SPARSE_TEXT,preserve_interword_spaces:'1'});const parsed=[];for(active=0;active<selectedFiles.length;active++){progress('Preparing photo '+(active+1)+' of '+selectedFiles.length+'…');const canvas=await prepare(selectedFiles[active]),{data}=await worker.recognize(canvas,{}, {text:true,blocks:true}),words=wordsFrom(data);let item=words.length?PNROCR.parseWords(words,canvas.width,canvas.height,$('asOf').value,$('ocr-layout').value):PNROCR.parseText(data.text||'',$('asOf').value);if(!item.rows.length&&!item.blocked)item=PNROCR.parseText(data.text||'',$('asOf').value);parsed.push(item);}show(PNROCR.mergeParsed(parsed));}catch(e){progress('OCR could not finish: '+e.message+' You can paste text below or enter positions manually.');}finally{if(worker)try{await worker.terminate();}catch(e){}busy=false;$('ocr-read').disabled=false;updateApply();}};
$('ocr-parse').onclick=()=>{if(busy)return;show(PNROCR.parseText($('ocr-text').value,$('asOf').value));};
$('ocr-rows').addEventListener('input',e=>{const f=e.target.dataset.field,row=e.target.closest('tr');if(!f||!row)return;const r=rows[+row.dataset.ocrRow];if(f==='confirmed')r.confirmed=e.target.checked;else{r[f]=['kind','expiry'].includes(f)?e.target.value:e.target.value===''?'':Number(e.target.value);r.confirmed=false;if(f==='mark')r.priceSource='Manual mark';row.querySelector('[data-field="confirmed"]').checked=false;if((f==='bid'||f==='ask')&&r.bid!==''&&r.ask!==''&&+r.ask>=+r.bid){r.mark=(+r.bid + +r.ask)/2;r.priceSource='Bid/ask midpoint';row.querySelector('[data-field="mark"]').value=r.mark;}}updateApply();});
$('ocr-rows').addEventListener('change',e=>{if(e.target.dataset.field==='confirmed'){const row=e.target.closest('tr');rows[+row.dataset.ocrRow].confirmed=e.target.checked;updateApply();}});
$('ocr-rows').addEventListener('click',e=>{const b=e.target.closest('[data-ocr-remove]');if(b){rows.splice(+b.dataset.ocrRemove,1);render();}});
$('ocr-add').onclick=()=>{rows.push({kind:'call',qty:'',expiry:'',strike:'',bid:'',ask:'',mark:'',iv:'',entry:'',warnings:['manually added row'],confirmed:false});render();};
$('ocr-apply').onclick=()=>{updateApply();if($('ocr-apply').disabled)return;try{const side=$('ocr-target').value,append=$('ocr-mode').value==='append';const fields=$('ocr-fields').checked?{symbol:$('ocr-symbol').value,spot:$('ocr-spot').value===''?'':+$('ocr-spot').value,nlv:$('ocr-nlv').value===''?'':+$('ocr-nlv').value}:null;for(const r of rows){if(!Number.isFinite(PNR.dateDays($('asOf').value,r.expiry))||PNR.dateDays($('asOf').value,r.expiry)<=0)throw Error('Every imported expiration must be after the snapshot date.');if(r.ask!==''&&r.bid!==''&&r.ask<r.bid)throw Error('An ask is below its bid; correct the quote first.');}if(fields&&((fields.spot!==''&&!(fields.spot>0))||(fields.nlv!==''&&!(fields.nlv>0))))throw Error('Detected spot and NLV must be positive or blank.');if(!append&&window.PNRLab.snapshot()[side].length&&!confirm('Replace the '+side+' table with '+rows.length+' reviewed legs?'))return;window.PNRLab.importRows(rows.map(r=>({kind:r.kind,qty:+r.qty,expiry:r.expiry,strike:+r.strike,mark:+r.mark,iv:'',entry:r.entry??'',priceSource:r.priceSource||'Manual mark'})),side,append,fields);progress('Imported '+rows.length+' reviewed legs into '+side+'. Review account NLV and click Calculate comparison.');$('ocr-review').hidden=true;rows=[];}catch(e){progress('Import blocked: '+e.message);}};
})();
