(function(){'use strict';
const $=id=>document.getElementById(id);let rows=[],previewURL=null,busy=false,enginePromise=null,selectedFile=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function progress(text){$('ocr-progress').textContent=text;}
function updateApply(){const date=/^\d{4}-\d{2}-\d{2}$/;$('ocr-apply').disabled=busy||!rows.length||rows.some(r=>!r.confirmed||r.qty===''||!Number.isInteger(+r.qty)||+r.qty===0||!date.test(r.expiry)||!(+r.strike>0)||!(+r.mark>0));}
function render(){$('ocr-review').hidden=false;$('ocr-rows').innerHTML=rows.map((r,i)=>`<tr data-ocr-row="${i}"><td><input data-field="confirmed" type="checkbox" ${r.confirmed?'checked':''} aria-label="Confirm extracted row ${i+1}"></td><td><select data-field="kind" aria-label="Extracted row ${i+1} type"><option value="call" ${r.kind==='call'?'selected':''}>Call</option><option value="put" ${r.kind==='put'?'selected':''}>Put</option></select></td>${['qty','expiry','strike','bid','ask','last','entry','mark'].map(k=>`<td><input data-field="${k}" type="${k==='expiry'?'date':'number'}" ${k==='expiry'?'':`step="${k==='qty'?1:'any'}"`} value="${esc(r[k])}" aria-label="Extracted row ${i+1} ${k}"></td>`).join('')}<td class="ocr-warnings">${esc((r.warnings||[]).join(' · ')||'Verify all fields')}</td><td><button data-ocr-remove="${i}" class="remove" aria-label="Remove extracted row ${i+1}">×</button></td></tr>`).join('');updateApply();}
function show(parsed){rows=parsed.rows;$('ocr-symbol').value=parsed.symbol||'';$('ocr-spot').value=parsed.spot||'';$('ocr-nlv').value=parsed.nlv||'';$('ocr-text').value=parsed.text||'';$('ocr-fields').checked=false;render();progress(parsed.message|| (rows.length?'Found '+rows.length+' candidate legs. Check every row and confirm the quantity sign, year, strike and midpoint.':'No clear positions-list rows found. Use the text fallback, crop to the positions list, or add review rows manually.'));}
function loadEngine(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(enginePromise)return enginePromise;enginePromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';s.onload=()=>{if(window.Tesseract)resolve(window.Tesseract);else{enginePromise=null;reject(Error('OCR engine failed to initialize.'));}};s.onerror=()=>{enginePromise=null;s.remove();reject(Error('Cannot download OCR engine. Check internet access or use the text fallback.'));};document.head.appendChild(s);});return enginePromise;}
function selectImage(file,source='image'){if(!file)return;if(!(file.type||'').startsWith('image/')){progress('Choose an image, not a document.');return;}selectedFile=file;progress('Selected '+(file.name||source)+'. Choose the price-column layout, then tap Read selected image.');$('ocr-drop').classList.add('has-image');}
async function prepare(file){if(!(file.type||'').startsWith('image/'))throw Error('Choose a photo or screenshot image.');if(file.size>20000000)throw Error('Use an image under 20 MB.');if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);$('ocr-image').src=previewURL;const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('This browser could not decode the image. If it is HEIC, export it as JPEG or PNG and try again.'));image.src=previewURL;});if(image.width*image.height>30000000)throw Error('Image is too large. Crop it to the positions list.');const scale=Math.min(2,1800/image.width,4000/image.height),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);let sum=0,count=0;for(let i=0;i<pixels.data.length;i+=400){sum+=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];count++;}const invert=sum/count<128;for(let i=0;i<pixels.data.length;i+=4){let g=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];if(invert)g=255-g;g=Math.max(0,Math.min(255,(g-128)*1.7+128));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=g;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);return canvas;}
function wordsFrom(data){const words=[];for(const block of data.blocks||[])for(const paragraph of block.paragraphs||[])for(const line of paragraph.lines||[])for(const word of line.words||[])words.push(word);return words;}
$('screenshot-file').onchange=e=>selectImage(e.target.files[0],'photo');
$('camera-file').onchange=e=>selectImage(e.target.files[0],'camera photo');
for(const name of ['dragenter','dragover'])$('ocr-drop').addEventListener(name,e=>{e.preventDefault();$('ocr-drop').classList.add('dragging');});
for(const name of ['dragleave','drop'])$('ocr-drop').addEventListener(name,e=>{e.preventDefault();$('ocr-drop').classList.remove('dragging');if(name==='drop')selectImage(e.dataTransfer?.files?.[0],'dropped image');});
$('ocr-drop').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target===$('ocr-drop')){$('screenshot-file').click();e.preventDefault();}});
async function pasteImage(){try{if(!navigator.clipboard?.read)throw Error('Clipboard image access is unavailable here. Use Choose photo instead.');const items=await navigator.clipboard.read();for(const item of items)for(const type of item.types)if(type.startsWith('image/')){selectImage(await item.getType(type),'pasted image');return;}throw Error('The clipboard does not contain an image.');}catch(e){progress(e.message);}}
$('ocr-paste').onclick=pasteImage;
if(document.addEventListener)document.addEventListener('paste',e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(item)selectImage(item.getAsFile(),'pasted image');});
$('ocr-read').onclick=async()=>{if(busy)return;const file=selectedFile||$('screenshot-file').files?.[0]||$('camera-file').files?.[0];if(!file){progress('Choose, take, paste or drop a screenshot first.');return;}let worker=null;busy=true;$('ocr-read').disabled=true;updateApply();try{progress('Preparing screenshot…');const canvas=await prepare(file);progress('Downloading OCR engine and English model…');const T=await loadEngine();worker=await T.createWorker('eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@6.0.0',logger:m=>progress(m.status+(m.progress!=null?' · '+Math.round(m.progress*100)+'%':''))});await worker.setParameters({tessedit_pageseg_mode:T.PSM.SPARSE_TEXT,preserve_interword_spaces:'1'});const {data}=await worker.recognize(canvas,{}, {text:true,blocks:true});const words=wordsFrom(data);let parsed=words.length?PNROCR.parseWords(words,canvas.width,canvas.height,$('asOf').value,$('ocr-layout').value):PNROCR.parseText(data.text||'',$('asOf').value);if(!parsed.rows.length&&!parsed.blocked)parsed=PNROCR.parseText(data.text||'',$('asOf').value);show(parsed);}catch(e){progress('OCR could not finish: '+e.message+' You can paste text below or enter positions manually.');}finally{if(worker)try{await worker.terminate();}catch(e){}busy=false;$('ocr-read').disabled=false;updateApply();}};
$('ocr-parse').onclick=()=>{if(busy)return;show(PNROCR.parseText($('ocr-text').value,$('asOf').value));};
$('ocr-rows').addEventListener('input',e=>{const f=e.target.dataset.field,row=e.target.closest('tr');if(!f||!row)return;const r=rows[+row.dataset.ocrRow];if(f==='confirmed')r.confirmed=e.target.checked;else{r[f]=['kind','expiry'].includes(f)?e.target.value:e.target.value===''?'':Number(e.target.value);r.confirmed=false;if(f==='mark')r.priceSource='Manual mark';row.querySelector('[data-field="confirmed"]').checked=false;if((f==='bid'||f==='ask')&&r.bid!==''&&r.ask!==''&&+r.ask>=+r.bid){r.mark=(+r.bid + +r.ask)/2;r.priceSource='Bid/ask midpoint';row.querySelector('[data-field="mark"]').value=r.mark;}}updateApply();});
$('ocr-rows').addEventListener('change',e=>{if(e.target.dataset.field==='confirmed'){const row=e.target.closest('tr');rows[+row.dataset.ocrRow].confirmed=e.target.checked;updateApply();}});
$('ocr-rows').addEventListener('click',e=>{const b=e.target.closest('[data-ocr-remove]');if(b){rows.splice(+b.dataset.ocrRemove,1);render();}});
$('ocr-add').onclick=()=>{rows.push({kind:'call',qty:'',expiry:'',strike:'',bid:'',ask:'',mark:'',iv:'',entry:'',warnings:['manually added row'],confirmed:false});render();};
$('ocr-apply').onclick=()=>{updateApply();if($('ocr-apply').disabled)return;try{const side=$('ocr-target').value,append=$('ocr-mode').value==='append';const fields=$('ocr-fields').checked?{symbol:$('ocr-symbol').value,spot:$('ocr-spot').value===''?'':+$('ocr-spot').value,nlv:$('ocr-nlv').value===''?'':+$('ocr-nlv').value}:null;for(const r of rows){if(!Number.isFinite(PNR.dateDays($('asOf').value,r.expiry))||PNR.dateDays($('asOf').value,r.expiry)<=0)throw Error('Every imported expiration must be after the snapshot date.');if(r.ask!==''&&r.bid!==''&&r.ask<r.bid)throw Error('An ask is below its bid; correct the quote first.');}if(fields&&((fields.spot!==''&&!(fields.spot>0))||(fields.nlv!==''&&!(fields.nlv>0))))throw Error('Detected spot and NLV must be positive or blank.');if(!append&&window.PNRLab.snapshot()[side].length&&!confirm('Replace the '+side+' table with '+rows.length+' reviewed legs?'))return;window.PNRLab.importRows(rows.map(r=>({kind:r.kind,qty:+r.qty,expiry:r.expiry,strike:+r.strike,mark:+r.mark,iv:'',entry:r.entry??'',priceSource:r.priceSource||'Manual mark'})),side,append,fields);progress('Imported '+rows.length+' reviewed legs into '+side+'. Review account NLV and click Calculate comparison.');$('ocr-review').hidden=true;rows=[];}catch(e){progress('Import blocked: '+e.message);}};
})();
